---
# tasks file for nginx
    - name: 'install nginx'    
      apt:
        update_cache: true
        force_apt_get: true
        name: 'nginx'
        state: 'present'
      become: true  
    - name: 'copy  nginx config'
      template: 
        src: 'nginx.conf.j2'
        dest: '/etc/nginx/sites-available/wordpress'
        owner: '{{nginx_user}}'
        group: '{{nginx_group}}'
        mode: '0644'
      become: true
    - name: 'Create symbolic link'
      ansible.builtin.file:
        src: '/etc/nginx/sites-available/wordpress'
        dest: '/etc/nginx/sites-enabled/wordpress'
        state: 'link'
      become: true
    - name: 'Delete default files'
      ansible.builtin.file:
        path: '/etc/nginx/sites-enabled/default'
        state: 'absent'
      become: true
    - name: 'Ensure that nginx started'
      service: 'name=nginx state=started'
      become: true
   

